# action.yml
name: okareo-action
description: Setup the Okareo CLI to continuously evaluate your model integrations
inputs:
  version: 
    description: 'The version of the Okareo CLI to use'
    required: false
    default: '0.0.8'
#runs:
#  using: 'docker'
#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.version }}
runs:
  using: node20
  main: dist/index.js
