# action.yml
name: 'Okareo CI/CD'
description: 'Setup the Okareo CLI to continuously evaluate your model integrations'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  version: 
    description: 'The version of the Okareo CLI to use'
    required: false
    default: '0.0.12'
#runs:
#  using: 'docker'
#  image: 'Dockerfile'
#  args:
#    - ${{ inputs.version }}
runs:
  using: 'node20'
  main: 'dist/index.js'
