name: Tests

on:
  push:
    branches:
    - experiment
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Okareo Action
      uses: ./
      with:
        version: '0.0.8'

    - name: Capture okareo version installed
      run: |
        echo $PATH
        which okareo
        okareo --version
