name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['0.0.9']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Okareo Action
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Validate that the Okareo CLI is available
      run: |
        echo $PATH

    - name: Capture okareo version installed
      run: |
        export OKAREO_VERSION=$( okareo -v )
        echo 'OKAREO_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        okareo -v >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Debug OKAREO_VERSION_INSTALLED
      run: | 
        echo "OKAREO_VERSION_INSTALLED=$OKAREO_VERSION_INSTALLED"
        echo "OKAREO_VERSION_EXPECTED=$OKAREO_VERSION_EXPECTED"

    - name: Verify
      shell: python
      env:
        OKAREO_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["OKAREO_VERSION_EXPECTED"] in os.environ["OKAREO_VERSION_INSTALLED"])
        )
