name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['0.0.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Okareo Action
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Capture okareo version installed
      run: |
        which okareo-cli
        okareo-cli version
        ./okareo-cli help
        export OKAREO_VERSION=$( okareo-cli version )
        echo 'OKAREO_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        okareo-cli version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        OKAREO_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["OKAREO_VERSION_EXPECTED"] in os.environ["OKAREO_VERSION_INSTALLED"])
        )
