name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['0.0.10']
    env:
      OKAREO_VERSION_EXPECTED: ${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Okareo Action
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Validate that the Okareo CLI is available
      run: |
        echo $PATH

    - name: Capture okareo version installed
      run: echo "OKAREO_VERSION_INSTALLED=$(okareo -v)" >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        OKAREO_VERSION_EXPECTED: ${{ env.OKAREO_VERSION_EXPECTED }}
        OKAREO_VERSION_INSTALLED: ${{ env.OKAREO_VERSION_INSTALLED }}
      run: |
        import sys, os
        expected_version = 'v'+os.getenv("OKAREO_VERSION_EXPECTED")
        installed_version = os.getenv("OKAREO_VERSION_INSTALLED")
        print(f"Expected version: {expected_version}")
        print(f"Installed version: {installed_version}")
        sys.exit(int(expected_version != installed_version))