name: Tests

on:
  push:
    branches:
    - experiment
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate that the Okareo CLI is available
      run: |
        echo $PATH

    - name: Capture okareo version installed
      run: |
        export OKAREO_VERSION=$( bin/okareo -v )
        echo 'OKAREO_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        bin/okareo -v >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        OKAREO_VERSION_EXPECTED: 'v0.0.8'
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["OKAREO_VERSION_EXPECTED"] in os.environ["OKAREO_VERSION_INSTALLED"])
        )
